### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [Servicerobotics-Ulm/SmartMDSD-Toolchain#11]
Hello Eclipse SmartMDSD team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Eclipse SmartMDSD project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by alex-lotz** [comment]
Hi Tamas,

thank you for the offer, we are definitely interested. At the moment we are actually moving our code-base to our new Eclipse Project:

https://projects.eclipse.org/projects/modeling.smartmdsd

Here is the requested information:

```
<tr>
	<td><a href="https://projects.eclipse.org/projects/modeling.smartmdsd">Eclipse SmartMDSD Toolchain</a></td>
	<td>The SmartMDSD Toolchain is an Eclipse-based Integrated Development Environment (IDE) for the model-driven development of component-based robotics software. The SmartMDSD Toolchain provides support and guidance to apply structures and best-practices for the composition of software building blocks to robotics applications.</td>
	<td>EPL-2.0</td>
	<td>Eclipse Modeling Project</td>
	<td>Alex Lotz, Dennis Stampfer, Matthias Lutz, and Christian Schlegel</td>
</tr>
```

Cheers,
Alex

**Comment by miklossy** [comment]
Thank you @alex-lotz !

**Comment by miklossy** [comment]
The `Eclipse SmartMDSD Toolchain` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
